# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import transport_pb2 as transport__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in transport_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TransportServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStops = channel.unary_unary(
                '/TransportService/GetStops',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=transport__pb2.GetStopsResponse.FromString,
                _registered_method=True)
        self.GetStopRoutes = channel.unary_unary(
                '/TransportService/GetStopRoutes',
                request_serializer=transport__pb2.StopRequest.SerializeToString,
                response_deserializer=transport__pb2.GetStopRoutesResponse.FromString,
                _registered_method=True)
        self.GetRouteDetails = channel.unary_unary(
                '/TransportService/GetRouteDetails',
                request_serializer=transport__pb2.RouteRequest.SerializeToString,
                response_deserializer=transport__pb2.GetRouteDetailsResponse.FromString,
                _registered_method=True)
        self.StreamVehiclePositions = channel.unary_stream(
                '/TransportService/StreamVehiclePositions',
                request_serializer=transport__pb2.VehicleStreamRequest.SerializeToString,
                response_deserializer=transport__pb2.VehiclePosition.FromString,
                _registered_method=True)


class TransportServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetStops(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStopRoutes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRouteDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamVehiclePositions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransportServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStops': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStops,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=transport__pb2.GetStopsResponse.SerializeToString,
            ),
            'GetStopRoutes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStopRoutes,
                    request_deserializer=transport__pb2.StopRequest.FromString,
                    response_serializer=transport__pb2.GetStopRoutesResponse.SerializeToString,
            ),
            'GetRouteDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRouteDetails,
                    request_deserializer=transport__pb2.RouteRequest.FromString,
                    response_serializer=transport__pb2.GetRouteDetailsResponse.SerializeToString,
            ),
            'StreamVehiclePositions': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamVehiclePositions,
                    request_deserializer=transport__pb2.VehicleStreamRequest.FromString,
                    response_serializer=transport__pb2.VehiclePosition.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TransportService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('TransportService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TransportService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetStops(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TransportService/GetStops',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            transport__pb2.GetStopsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStopRoutes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TransportService/GetStopRoutes',
            transport__pb2.StopRequest.SerializeToString,
            transport__pb2.GetStopRoutesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRouteDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TransportService/GetRouteDetails',
            transport__pb2.RouteRequest.SerializeToString,
            transport__pb2.GetRouteDetailsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamVehiclePositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/TransportService/StreamVehiclePositions',
            transport__pb2.VehicleStreamRequest.SerializeToString,
            transport__pb2.VehiclePosition.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
